using System.Numerics;
using Content.Client.UserInterface.Systems.Chat.Widgets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Screens;

[GenerateTypedNameReferences]
public sealed partial class SeparatedChatGameScreen : InGameScreen
{
    public SeparatedChatGameScreen()
    {
        RobustXamlLoader.Load(this);

        AutoscaleMaxResolution = new Vector2i(1080, 770);

        SetAnchorPreset(LeftContainer, LayoutPreset.Wide);
        SetAnchorPreset(ViewportContainer, LayoutPreset.Wide);
        SetAnchorPreset(MainViewport, LayoutPreset.Wide);
        SetAnchorAndMarginPreset(Ghost, LayoutPreset.BottomWide, margin: 80);

        SetAnchorPreset(Background, LayoutPreset.Wide);
        SetAnchorPreset(Inventory, LayoutPreset.BottomLeft);
        SetAnchorPreset(Actions, LayoutPreset.TopRight);
        SetAnchorPreset(Hotbar, LayoutPreset.CenterLeft);
        SetAnchorPreset(Alerts, LayoutPreset.TopLeft);
        SetAnchorPreset(CombatMode, LayoutPreset.BottomRight);
        SetAnchorPreset(PartStatus, LayoutPreset.BottomRight);
        SetAnchorPreset(Targeting, LayoutPreset.BottomLeft);

        LeftContainer.OnSplitResizeFinished += () =>
            OnChatResized?.Invoke(new Vector2(LeftContainer.SplitFraction, 0));
    }

    public override ChatBox ChatBox => GetWidget<ChatBox>()!;

    public override void SetChatSize(Vector2 size)
    {

    }
}
