using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._White.UserInterface.Systems.CombatMode.Widgets;

[GenerateTypedNameReferences]
public sealed partial class CombatModeGui : UIWidget
{
    public static SpriteSpecifier Sprite = new SpriteSpecifier.Rsi(new ("/Textures/_White/Interface/Misc/screen_gen.rsi"), "flash");

    public CombatModeGui()
    {
        RobustXamlLoader.Load(this);
        var controller = UserInterfaceManager.GetUIController<CombatModeUIController>();

        CombatModeButton.OnToggled += _ => controller.ToggleCombatMode();

        CombatModeFlash.SetFromSpriteSpecifier(Sprite);
        CombatModeFlash.DisplayRect.TextureScale = new (2, 2);
    }

    public void OnCombatModeUpdated(bool inCombatMode)
    {
        // CARMINE - .2 NOTE | WD uses a different engine version and some wizardry to fetch "combat_on" as a fucking texture, but we can't or I'm too stupid to figure it out
        // so we're just ghonna have one texture and the little screen_gen as an indicator, and get our spriters to whip something later.
        // CombatModeButton.TexturePath = inCombatMode ? "combat_on" :  "combat_off";
        CombatModeFlash.Visible = inCombatMode;
        CombatModeButton.SetClickPressed(inCombatMode);
    }
}

